if (!require(pacman)) install.packages("pacman"); library(pacman)
p_load("data.table")
p_load("magrittr")
p_load("ggplot2")
p_load("dplyr")
p_load("ggplot2")
p_load("forcats")
p_install_gh("MRCIEU/TwoSampleMR")