if (!require(pacman)) install.packages("pacman"); library(pacman)
p_load("data.table")
p_load("ggplot2")
p_load("lmtest")
p_load("sandwich")
p_load("furrr")
p_load("devtools")
p_load("MendelianRandomization")
p_install_gh("MRCIEU/TwoSampleMR")
p_install_gh("MRCIEU/ieugwasr")